---
layout: blog
topic: "01"
short-topic: Asking Good Questions
due-date: 2023-01-26
root: ../../
---

## Prompt:

Asking good questions is a valuable skill to have - asking questions in an online setting is both easier and harder than asking questions in person: we can prepare to ask a question but we are also expected to prepare.
The links posted here give some advice on how to ask good questions:

- stackoverflow's [Asking a good question](http://stackoverflow.com/help/how-to-ask)

- R's [Posting guidelines](https://www.r-project.org/posting-guide.html)

- [minimal complete verifiable example](https://stackoverflow.com/help/mcve), [minimal reproducible example](https://www.tidyverse.org/help/)

Follow these links and read through the advice given, then

1. **Find at least une unanswered questions on stackoverflow or R help and provide an answer for the community.**

Write a blog post answering the following questions: 

2. **Document which question you answered and link to your answer on stackoverflow or R help.**

3. **Relate your experience of answering the question to your reading. **
 

<!--Go to [https://github.com/Stat585-at-ISU/blog](https://github.com/Stat585-at-ISU/blog) for instructions about how to prepare and submit your blog post.-->
Instructions to follow.
